import {StyleSheet} from 'react-native';
import theme from '../../theme/index';
import {
  responsiveHeight,
  responsiveWidth,
} from 'react-native-responsive-dimensions';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.color.background,
  },
  cross: {
    width: responsiveWidth(12),
    height: responsiveHeight(6),
    justifyContent: 'center',
    marginTop: responsiveHeight(2),
    marginLeft: 10,
  },
  section1: {
    alignItems: 'center',
    justifyContent: 'center',
    // backgroundColor: 'red',
    paddingHorizontal: 10,
  },
  logo: {
    width: responsiveWidth(30),
    height: responsiveHeight(20),
    resizeMode: 'cover',
  },
  title: {
    fontSize: 20,
    fontFamily: theme.fonts.fontBold,
    color: theme.color.title,
    alignSelf: 'center',
    marginTop: -15,
  },
  section2: {
    alignItems: 'center',
    justifyContent: 'center',
    // backgroundColor: 'yellow',
    alignSelf: 'center',
    paddingHorizontal: 20,
    width: responsiveWidth(90),
    paddingVertical: 10,
    marginTop: responsiveHeight(17),
  },
  title2: {
    fontSize: 14,
    fontFamily: theme.fonts.fontMedium,
    color: theme.color.title,
    alignSelf: 'center',
  },
  InputLoc: {
    borderBottomWidth: 0.7,
    borderColor: theme.color.title,
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    height: responsiveHeight(5),
    fontFamily: 'Inter-Regular',
    backgroundColor: theme.color.background,
  },
  ChargesTextloc: {
    fontSize: 13,
    lineHeight: 20,
    color: theme.color.title,
    textTransform: 'capitalize',
    fontFamily: theme.fonts.fontNormal,
  },
  BottomButton: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.color.button1,
    height: responsiveHeight(5.5),
    borderRadius: 7,
    alignSelf: 'center',
    marginTop: 50,
    elevation: 4,
  },
  buttonTextBottom: {
    color: theme.color.buttonText,
    fontSize: 15,
    fontFamily: theme.fonts.fontBold,
    textTransform: 'capitalize',
  },
  LinearGradient: {
    height: '100%',
    width: '100%',
    borderRadius: 7,
    justifyContent: 'center',
    alignItems: 'center',
  },
  BottomButton2: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    height: responsiveHeight(5.5),
    backgroundColor: theme.color.background,
    borderRadius: 7,
    alignSelf: 'center',
    marginTop: 20,
    elevation: 4,
    flexDirection: 'row',
    borderWidth: 0.7,
    borderColor: theme.color.button1,
  },
  LinearGradient2: {
    height: '100%',
    width: '100%',
    borderRadius: 7,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
  },
});
